#!/bin/bash

# exported with command
# gsettings list-recursively org.gnome.desktop.wm.keybindings | xargs -L 1 echo gsettings set $1 > anthony.keybindings
#

gsettings set org.gnome.desktop.wm.keybindings cycle-windows-backward [<Shift><Alt>Escape]
gsettings set org.gnome.desktop.wm.keybindings minimize [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7 [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8 [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-9 [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-left [<Super><Shift>Left]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-10 [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-11 [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-12 [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-center @as []
gsettings set org.gnome.desktop.wm.keybindings unmaximize [<Super>Down]
gsettings set org.gnome.desktop.wm.keybindings panel-main-menu [<Super>s]
gsettings set org.gnome.desktop.wm.keybindings cycle-windows [<Alt>Escape]
gsettings set org.gnome.desktop.wm.keybindings cycle-panels-backward [<Shift><Control><Alt>Escape]
gsettings set org.gnome.desktop.wm.keybindings panel-run-dialog [<Alt>F2]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down [<Control><Alt>Down]
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-ne [<Control><Alt>KP_Prior]
gsettings set org.gnome.desktop.wm.keybindings move-to-side-e [<Control><Alt>KP_Right]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right [<Shift><Control><Alt>Right]
gsettings set org.gnome.desktop.wm.keybindings always-on-top @as []
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up [<Shift><Control><Alt>Up]
gsettings set org.gnome.desktop.wm.keybindings raise [disabled]
gsettings set org.gnome.desktop.wm.keybindings maximize [<Super>Up]
gsettings set org.gnome.desktop.wm.keybindings cycle-group-backward [<Shift><Alt>F6]
gsettings set org.gnome.desktop.wm.keybindings move-to-side-n [<Control><Alt>KP_Up]
gsettings set org.gnome.desktop.wm.keybindings move-to-side-s [<Control><Alt>KP_Down]
gsettings set org.gnome.desktop.wm.keybindings maximize-horizontally [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-side-w [<Control><Alt>KP_Left]
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-nw [<Control><Alt>KP_Home]
gsettings set org.gnome.desktop.wm.keybindings switch-windows [disabled]
gsettings set org.gnome.desktop.wm.keybindings begin-move [<Alt>F7]
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-down [<Super><Shift>Down]
gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left [<Shift><Control><Alt>Left]
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-se [<Control><Alt>KP_Next]
gsettings set org.gnome.desktop.wm.keybindings activate-window-menu [<Alt>space]
gsettings set org.gnome.desktop.wm.keybindings switch-input-source [<Super>space]
gsettings set org.gnome.desktop.wm.keybindings toggle-above @as []
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-right [<Super><Shift>Right]
gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward [<Shift>Alt_L]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-last [<Super><Shift>End]
gsettings set org.gnome.desktop.wm.keybindings lower [disabled]
gsettings set org.gnome.desktop.wm.keybindings cycle-panels [<Control><Alt>Escape]
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen [disabled]
gsettings set org.gnome.desktop.wm.keybindings toggle-on-all-workspaces [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-up [<Super><Shift>Up]
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-sw [<Control><Alt>KP_End]
gsettings set org.gnome.desktop.wm.keybindings toggle-shaded [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 [<Super>Home]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 [disabled]
gsettings set org.gnome.desktop.wm.keybindings raise-or-lower @as []
gsettings set org.gnome.desktop.wm.keybindings switch-panels [<Control><Alt>Tab]
gsettings set org.gnome.desktop.wm.keybindings switch-panels-backward [<Shift><Control><Alt>Tab]
gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward [<Shift><Super>Tab, <Shift><Alt>Tab]
gsettings set org.gnome.desktop.wm.keybindings maximize-vertically [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 [disabled]
gsettings set org.gnome.desktop.wm.keybindings show-desktop [<Super>d]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8 [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-applications [<Super>Tab, <Alt>Tab]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-10 [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-11 [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-12 [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left [<Control><Alt>Left]
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized [disabled]
gsettings set org.gnome.desktop.wm.keybindings set-spew-mark @as []
gsettings set org.gnome.desktop.wm.keybindings begin-resize [<Alt>F8]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down [<Shift><Control><Alt>Down]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-last [<Super>End]
gsettings set org.gnome.desktop.wm.keybindings switch-group-backward [<Shift><Super>Above_Tab, <Shift><Alt>Above_Tab]
gsettings set org.gnome.desktop.wm.keybindings switch-group [<Super>Above_Tab, <Alt>Above_Tab]
gsettings set org.gnome.desktop.wm.keybindings cycle-group [<Alt>F6]
gsettings set org.gnome.desktop.wm.keybindings close [<Alt>F4]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up [<Control><Alt>Up]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 [<Shift><Super>Home]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 [disabled]
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 [disabled]
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right [<Control><Alt>Right]
